# test.andon.yml
pipelines:
  pipe1:
    group: eCommerce
    materials:
      zuul:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/tieto-devops-demos/microservice-demo-zuul-server.git
    stages:
      - build: # name of stage
          jobs:
            maven: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                    - "-c"
                    - "echo foo"
